### ISSUE TITLE
文件显示问题

### ISSUE THREAD

**Issue by wnbh** [xiaokaixuan/pikpak#5]
自己部署的文件加载不出来，空白一片；更新了cf-workers也是一样；使用你的登录就没问题，更改你的代理设置为我的cf代理链接之后，你的也加载不出文件了；把你的代理链接还我部署的里面也还是加载不出文件来。

**Comment by xiaokaixuan** [comment]
> 自己部署的文件加载不出来，空白一片；更新了cf-workers也是一样；使用你的登录就没问题，更改你的代理设置为我的cf代理链接之后，你的也加载不出文件了；把你的代理链接还我部署的里面也还是加载不出文件来。

刚登了下你部署的，没问题啊。。。https://wnbh.github.io/pikpak

**Comment by wnbh** [comment]
> > 自己部署的文件加载不出来，空白一片；更新了cf-workers也是一样；使用你的登录就没问题，更改你的代理设置为我的cf代理链接之后，你的也加载不出文件了；把你的代理链接还我部署的里面也还是加载不出文件来。
> 
> 刚登了下你部署的，没问题啊。。。https://wnbh.github.io/pikpak

离大谱 我之前确实是加载不出来 现在好像又行了。。。

**Comment by xiaokaixuan** [comment]
> > > 自己部署的文件加载不出来，空白一片；更新了cf-workers也是一样；使用你的登录就没问题，更改你的代理设置为我的cf代理链接之后，你的也加载不出文件了；把你的代理链接还我部署的里面也还是加载不出文件来。
> > 
> > 
> > 刚登了下你部署的，没问题啊。。。https://wnbh.github.io/pikpak
> 
> 离大谱 我之前确实是加载不出来 现在好像又行了。。。

之间空白是`cf-worker/index.js`的问题，已经修复过了，估计你没及时更新。

**Comment by wnbh** [comment]
> > > > 自己部署的文件加载不出来，空白一片；更新了cf-workers也是一样；使用你的登录就没问题，更改你的代理设置为我的cf代理链接之后，你的也加载不出文件了；把你的代理链接还我部署的里面也还是加载不出文件来。
> > > 
> > > 
> > > 刚登了下你部署的，没问题啊。。。https://wnbh.github.io/pikpak
> > 
> > 
> > 离大谱 我之前确实是加载不出来 现在好像又行了。。。
> 
> 之间空白是`cf-worker/index.js`的问题，已经修复过了，估计你没及时更新。

更新了也那样 可能是cf-worker更新了也要等一段时间才生效吧
